package com.collegesearch.domain.school;
// Generated Jul 22, 2016 11:35:09 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GraduateSchoolMajorId generated by hbm2java
 */
@Embeddable
public class GraduateSchoolMajorId implements java.io.Serializable {

	private int schoolId;
	private String majorId;

	public GraduateSchoolMajorId() {
	}

	public GraduateSchoolMajorId(int schoolId, String majorId) {
		this.schoolId = schoolId;
		this.majorId = majorId;
	}

	@Column(name = "School_id", nullable = false)
	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "Major_id", nullable = false, length = 10)
	public String getMajorId() {
		return this.majorId;
	}

	public void setMajorId(String majorId) {
		this.majorId = majorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GraduateSchoolMajorId))
			return false;
		GraduateSchoolMajorId castOther = (GraduateSchoolMajorId) other;

		return (this.getSchoolId() == castOther.getSchoolId())
				&& ((this.getMajorId() == castOther.getMajorId()) || (this.getMajorId() != null
						&& castOther.getMajorId() != null && this.getMajorId().equals(castOther.getMajorId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSchoolId();
		result = 37 * result + (getMajorId() == null ? 0 : this.getMajorId().hashCode());
		return result;
	}

}
