package com.collegesearch.domain.school;

// Generated Aug 10, 2015 3:42:22 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major", catalog = "School")
public class Major implements java.io.Serializable {

	private static final long serialVersionUID = -804990758703320L;
	private String id;
	private String name;
	
	public Major() {
	}
	
	public Major(String id) {
		this.id = id;
	}

	public Major(String id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
/*	
    private Set<Applicant> schools = new HashSet<Applicant>(0);
	private Set<BestSchoolMajor> bestSchoolMajors = new HashSet<BestSchoolMajor>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name="best_school_major",
			joinColumns = {@javax.persistence.JoinColumn(name = "MAJOR_ID")},
			inverseJoinColumns = {@javax.persistence.JoinColumn(name = "SCHOOL_ID")}
    )	
	public Set<Applicant> getSchools() {
		return this.schools;
	}

	public void setSchools(Set<Applicant> schools) {
		this.schools = schools;
	}
	
	public void addSchools(Applicant school){
		if(schools == null)
			schools = new HashSet<Applicant>();
		schools.add(school);
	}
*/
/*
	@OneToMany(fetch = FetchType.EAGER)
	@JoinColumn(name="major_id", updatable=false, insertable=false)
	public Set<BestSchoolMajor> getBestSchoolMajors() {
		return bestSchoolMajors;
	}

	public void setBestSchoolMajors(Set<BestSchoolMajor> bestSchoolMajors) {
		this.bestSchoolMajors = bestSchoolMajors;
	}
	*/
	
}
