package com.collegesearch.domain.school;

// Generated Jul 11, 2015 5:53:42 PM by Hibernate Tools 4.0.0

import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Boost;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.annotations.Store;

import com.collegesearch.domain.user.Applicant;
import com.collegesearch.util.school.SchoolUtil;


/**
 * SchoolId generated by hbm2java
 */
@Entity
@Table (name="School")
@Indexed
@Analyzer(impl = StandardAnalyzer.class)
public class School implements java.io.Serializable {

	private static final long serialVersionUID = 6749990758703320L;
	private Integer id;
	private String  name;
	private String  type;
	private String  city;
	private String  state;
	private String  setting;
	private Integer size;
	private Integer tuitionFee;
	private Integer instateTuitionFee;
	private Integer roomBoard;
	private String  applicationDeadline;
	private String  satActReceivedDeadline;
	private String  earlyDecisionDeadline;
	private Float   percentageClassesFewerThan20Students;
    private Float   percentageClassesMoreThan50Students;
    private Float   percentageClassesBetween25And50Students;
  	private Integer applicationFee;
	private Integer sat1Percentile25;
	private Integer sat1Percentile75;
	private Integer actPercentile25;
	private Integer actPercentile75;
	private String  satActNotRequired;
	private Integer numberOfRequiredSat2;
	private Float   averageGpa;
	private Float   acceptRate;
	private Integer averageFreshmanRetentionRate;
    private Integer sixYearGraduationRate;
	private Integer rankOverall;
	private Float   reputationScore;
	private String  selectivity;
	private Integer hsClassTop10Percentage;
	private Float   studentFacultyRatio;
	private String  category;
	private String  calendar;
	private String  Phone;
	private String  website;
	private Integer maxResults;
	private Integer totalCost;
	private Integer averageSAT;
	private SchoolInternationalApplication schoolInternationalApplication;
	private SchoolRankInSpeciality schoolRankInSpeciality;
	private Float likelihoodOfSuccess;
	private String applicationNote;
	private Set<Major> bestMajors = new HashSet<Major>();
	private Applicant randomApplicant;	
	
	
	@DocumentId
	@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
    
	@Field(index=Index.YES, analyze=Analyze.NO, store=Store.YES)
	@Boost(1.5f)
    @Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "City", length = 80)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Field(index=Index.YES, analyze=Analyze.NO, store=Store.YES)
	@Boost(1.5f)
	@Column(name = "State", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Setting", length = 15)
	public String getSetting() {
		return this.setting;
	}

	public void setSetting(String setting) {
		this.setting = setting;
	}

	@Column(name = "Size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Column(name = "Tuition_Fee")
	public Integer getTuitionFee() {
		return this.tuitionFee;
	}

	public void setTuitionFee(Integer tuitionFee) {
		this.tuitionFee = tuitionFee;
	}

	@Column(name = "In_State_Tuition_Fee")
	public Integer getInstateTuitionFee() {
		return instateTuitionFee;
	}

	public void setInstateTuitionFee(Integer instateTuitionFee) {
		this.instateTuitionFee = instateTuitionFee;
	}

	@Column(name = "Room_Board")
	public Integer getRoomBoard() {
		return this.roomBoard;
	}

	public void setRoomBoard(Integer roomBoard) {
		this.roomBoard = roomBoard;
	}

	@Column(name = "Application_Deadline", length = 10)
	public String getApplicationDeadline() {
		return this.applicationDeadline;
	}

	public void setApplicationDeadline(String applicationDeadline) {
		this.applicationDeadline = applicationDeadline;
	}

	@Column(name = "Application_Fee")
	public Integer getApplicationFee() {
		return this.applicationFee;
	}

	public void setApplicationFee(Integer applicationFee) {
		this.applicationFee = applicationFee;
	}

	@Column(name = "SAT1_percentile_25")
	public Integer getSat1Percentile25() {
		return this.sat1Percentile25;
	}

	public void setSat1Percentile25(Integer sat1Percentile25) {
		this.sat1Percentile25 = sat1Percentile25;
	}

	@Column(name = "SAT1_percentile_75")
	public Integer getSat1Percentile75() {
		return this.sat1Percentile75;
	}

	public void setSat1Percentile75(Integer sat1Percentile75) {
		this.sat1Percentile75 = sat1Percentile75;
	}
	
	@Column(name = "ACT_percentile_25")
	public Integer getActPercentile25() {
		return actPercentile25;
	}

	public void setActPercentile25(Integer actPercentile25) {
		this.actPercentile25 = actPercentile25;
	}

	@Column(name = "ACt_percentile_75")
	public Integer getActPercentile75() {
		return actPercentile75;
	}

	public void setActPercentile75(Integer actPercentile75) {
		this.actPercentile75 = actPercentile75;
	}
	
	/*
	@Transient
	public Integer getAdjustedSat1Standard() {
		if(sat1Percentile25 <= 0 || sat1Percentile75 <= 0) {
			adjustedSat1Standard = 0;
			return 0;
		}	
		float sat = 0.0f;
		if(acceptRate <= 10) 
		   sat = actPercentile75 * 1.2f; //for top 10 return 120% of Percentile75;
		else if(acceptRate > 10 && acceptRate <= 20) 
			  sat = actPercentile75 * 1.15f; //for top 10-25 return 115% of Percentile75
		else if(acceptRate > 20 && acceptRate <= 30) 
			   sat = actPercentile75 * 1.1f; //for top 20-30 return 110% of Percentile75
		else if(acceptRate > 30 && acceptRate <= 40)
			   sat = actPercentile75 * 1.05f; //for top 30-40 return 105% of Percentile75
		else if(acceptRate > 40 && acceptRate <= 50) 
			   sat = actPercentile75 * 1.0f;  //for top 40-50 return 100% of Percentile75
		else if(acceptRate > 50 && acceptRate <= 60) 
			   sat = actPercentile75 * 0.9f;  
		else if(acceptRate > 60 && acceptRate <= 70) //for top 40-60 return (Percentile25 + Percentile75)/2
			   sat = actPercentile75 * 0.8f;  //for top 60-70 return 80% of Percentile75
			//adjustedActStandard = (actPercentile25 + actPercentile75)/2; //for top 50-60 return 90% of Percentile75
		else if(acceptRate > 70)                     //for top > 60 Percentile25
			   sat = actPercentile25;
		adjustedSat1Standard = Math.round(sat);
		return adjustedSat1Standard;
	}

	public void setAdjustedSat1Standard(Integer adjustedSat1Standard) {
		this.adjustedSat1Standard = adjustedSat1Standard;
	}
	
	@Transient
	public boolean isSat1ScoreSatisfied(int sat1Score){
		if(getAdjustedSat1Standard() == 0 )
		   return false;	
		return (sat1Score >= getAdjustedSat1Standard());
	}
	
	@Transient
	public Integer getAdjustedActStandard() {
		if(actPercentile25 <= 0 || actPercentile75 <= 0) {
			adjustedActStandard = 0;
			return 0;
		}	
		float act = 0.0f;
		if(acceptRate <= 10) 
		   act = actPercentile75 * 1.2f; //for top 10 return 120% of Percentile75;
		else if(acceptRate > 10 && acceptRate <= 20) 
			  act = actPercentile75 * 1.15f; //for top 10-25 return 115% of Percentile75
		else if(acceptRate > 20 && acceptRate <= 30) 
			   act = actPercentile75 * 1.1f; //for top 20-30 return 110% of Percentile75
		else if(acceptRate > 30 && acceptRate <= 40)
			   act = actPercentile75 * 1.05f; //for top 30-40 return 105% of Percentile75
		else if(acceptRate > 40 && acceptRate <= 50) 
			   act = actPercentile75 * 1.0f;  //for top 40-50 return 100% of Percentile75
		else if(acceptRate > 50 && acceptRate <= 60) 
			   act = actPercentile75 * 0.9f;  
		else if(acceptRate > 60 && acceptRate <= 70) //for top 40-60 return (Percentile25 + Percentile75)/2
			   act = actPercentile75 * 0.8f;  //for top 60-70 return 80% of Percentile75
			//adjustedActStandard = (actPercentile25 + actPercentile75)/2; //for top 50-60 return 90% of Percentile75
		else if(acceptRate > 70)                     //for top > 60 Percentile25
			   act = actPercentile25;
		adjustedActStandard = Math.round(act);
		return adjustedActStandard;
	}

	public void setAdjustedActStandard(Integer adjustedActStandard) {
		this.adjustedActStandard = adjustedActStandard;
	}
	
	@Transient
	public boolean isActScoreSatisfied(int actScore){
		if(getAdjustedActStandard() == 0 )
		   return false;	
		return (actScore >= getAdjustedActStandard());
	}
	*/
	
	@Column(name="SAT_ACT_Not_Required", length=5)
	public String getSatActNotRequired() {
		return satActNotRequired;
	}

	public void setSatActNotRequired(String satActNotRequired) {
		this.satActNotRequired = satActNotRequired;
	}

	@Column(name = "SAT2_Number_Required")
	public Integer getNumberOfRequiredSat2() {
		return this.numberOfRequiredSat2;
	}

	public void setNumberOfRequiredSat2(Integer numberOfRequiredSat2) {
		this.numberOfRequiredSat2 = numberOfRequiredSat2;
	}
	
	@Column(name = "Average_GPA")
    public Float getAverageGpa() {
		return averageGpa;
	}

	public void setAverageGpa(Float averageGpa) {
		this.averageGpa = averageGpa;
	}

	@Column(name="Percentage_Classes_Fewer_Than_20_students", precision=12, scale=0)
    public Float getPercentageClassesFewerThan20Students() {
        return this.percentageClassesFewerThan20Students;
    }
    
    public void setPercentageClassesFewerThan20Students(Float percentageClassesFewerThan20Students) {
        this.percentageClassesFewerThan20Students = percentageClassesFewerThan20Students;
    }

    
    @Column(name="Percentage_Classes_More_Than_50_students", precision=12, scale=0)
    public Float getPercentageClassesMoreThan50Students() {
        return this.percentageClassesMoreThan50Students;
    }
    
    public void setPercentageClassesMoreThan50Students(Float percentageClassesMoreThan50Students) {
        this.percentageClassesMoreThan50Students = percentageClassesMoreThan50Students;
    }
    
    @Transient    
    public Float getPercentageClassesBetween25And50Students() {
	 	if(percentageClassesFewerThan20Students != null && percentageClassesFewerThan20Students > 0 &&
    	   percentageClassesMoreThan50Students != null && percentageClassesMoreThan50Students > 0)		
    	   percentageClassesBetween25And50Students = 100 - percentageClassesFewerThan20Students - percentageClassesMoreThan50Students;
    	   return percentageClassesBetween25And50Students;
    }

	public void setPercentageClassesBetween25And50Students(Float percentageClassesBetween25And50Students) {
		if(percentageClassesFewerThan20Students != null && percentageClassesFewerThan20Students > 0 &&
		   percentageClassesMoreThan50Students != null && percentageClassesMoreThan50Students > 0)		
		   percentageClassesBetween25And50Students = 100 - percentageClassesFewerThan20Students - percentageClassesMoreThan50Students;
		   this.percentageClassesBetween25And50Students = 100 - percentageClassesFewerThan20Students - percentageClassesMoreThan50Students;
	}

	@Column(name="SAT_ACT_Received_Deadline", length=10)
    public String getSatActReceivedDeadline() {
        return this.satActReceivedDeadline;
    }
    
    public void setSatActReceivedDeadline(String satActReceivedDeadline) {
        this.satActReceivedDeadline = satActReceivedDeadline;
    }

    
    @Column(name="Early_Decision_Deadline", length=10)
	public String getEarlyDecisionDeadline() {
		return earlyDecisionDeadline;
	}

	public void setEarlyDecisionDeadline(String earlyDecisionDeadline) {
		this.earlyDecisionDeadline = earlyDecisionDeadline;
	}
		
	@Column(name = "Accept_Rate")
	public Float getAcceptRate() {
		return this.acceptRate;
	}

	public void setAcceptRate(Float acceptRate) {
		this.acceptRate = acceptRate;
	}
	
	@Column(name = "Average_Freshman_Retention_Rate")
	public Integer getAverageFreshmanRetentionRate() {
		return averageFreshmanRetentionRate;
	}

	public void setAverageFreshmanRetentionRate(Integer averageFreshmanRetentionRate) {
		this.averageFreshmanRetentionRate = averageFreshmanRetentionRate;
	}

	@Column(name = "Six_Year_Graduation_Rate")
	public Integer getSixYearGraduationRate() {
		return sixYearGraduationRate;
	}

	public void setSixYearGraduationRate(Integer sixYearGraduationRate) {
		this.sixYearGraduationRate = sixYearGraduationRate;
	}

	@Column(name = "Rank_Overall")
	public Integer getRankOverall() {
		return this.rankOverall;
	}

	public void setRankOverall(Integer rankOverall) {
		this.rankOverall = rankOverall;
	}

	@Column(name = "Reputation_Score")
	public Float getReputationScore() {
		return this.reputationScore;
	}

	public void setReputationScore(Float reputationScore) {
		this.reputationScore = reputationScore;
	}

	@Column(name = "Selectivity", length = 15)
	public String getSelectivity() {
		return this.selectivity;
	}

	public void setSelectivity(String selectivity) {
		this.selectivity = selectivity;
	}

	@Column(name = "HS_Class_Top_10_Percentage")
	public Integer getHsClassTop10Percentage() {
		return this.hsClassTop10Percentage;
	}

	public void setHsClassTop10Percentage(Integer hsClassTop10Percentage) {
		this.hsClassTop10Percentage = hsClassTop10Percentage;
	}

	@Column(name = "Student_Faculty_Ratio")
	public Float getStudentFacultyRatio() {
		return this.studentFacultyRatio;
	}

	public void setStudentFacultyRatio(Float studentFacultyRatio) {
		this.studentFacultyRatio = studentFacultyRatio;
	}

	@Column(name = "Category", length = 40)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "Calendar", length = 10)
	public String getCalendar() {
		return this.calendar;
	}

	public void setCalendar(String calendar) {
		this.calendar = calendar;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return Phone;
	}

	public void setPhone(String phone) {
		Phone = phone;
	}
	
	@Column(name = "Website", length = 100)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Transient
	public Integer getMaxResults() {
		return maxResults;
	}

	public void setMaxResults(Integer maxResults) {
		this.maxResults = maxResults;
	}
 
	@Transient
	public Integer getTotalCost() {
		return totalCost;
	}
	
	public void setTotalCost(Integer totalCost) {
		this.totalCost = totalCost;
	}
	
	@Transient
	public Integer getAverageSAT() {
		return averageSAT;
	}

	public void setAverageSAT(Integer averageSAT) {
		this.averageSAT = averageSAT;
	}
	
	public void assignAverageSAT() {
		if(averageSAT == null){
		   if(sat1Percentile25 != null && sat1Percentile25 != 0 && sat1Percentile75 != null && sat1Percentile75 != 0)
		      averageSAT = (sat1Percentile25 + sat1Percentile75)/2;
		   else if(actPercentile25 != null && actPercentile25 != 0 && actPercentile75 != null && actPercentile75 != 0)
			  averageSAT = (SchoolUtil.convertActToSat(actPercentile25) + SchoolUtil.convertActToSat(actPercentile75))/2; 
	       }
	}

	@Transient
	public Float getLikelihoodOfSuccess() {
		return likelihoodOfSuccess;
	}

	public void setLikelihoodOfSuccess(Float likelihoodOfSuccess) {
		this.likelihoodOfSuccess = likelihoodOfSuccess;
	}
	
	@Transient	
	public String getApplicationNote() {
		return applicationNote;
	}

	public void setApplicationNote(String applicationNote) {
		this.applicationNote = applicationNote;
	}

	@Transient
	public Applicant getRandomApplicant() {
		return randomApplicant;
	}

	public void setRandomApplicant(Applicant randomApplicant) {
		this.randomApplicant = randomApplicant;
	}

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "best_school_major", catalog = "school", joinColumns = { 
			@javax.persistence.JoinColumn(name = "School_Id", nullable = false, updatable = false) }, 
			inverseJoinColumns = {@javax.persistence.JoinColumn(name = "Major_Id", nullable = false, updatable = false) })
	public Set<Major> getBestMajors() {
		return this.bestMajors;
	}

	public void setBestMajors(Set<Major> bestMajors) {
		this.bestMajors = bestMajors;
	}
   
	public void addBestMajors(Major major){
		if(bestMajors == null)
			bestMajors = new HashSet<Major>();
		bestMajors.add(major);
	}
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "school", cascade = CascadeType.ALL, orphanRemoval = true)
	//@Fetch(FetchMode.JOIN)
	//@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	@IndexedEmbedded
	public SchoolInternationalApplication getInternationalStudentApplication() {
		return schoolInternationalApplication;
	}

	public void setInternationalStudentApplication(
			SchoolInternationalApplication schoolInternationalApplication) {
		this.schoolInternationalApplication = schoolInternationalApplication;
	}
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "school", cascade = CascadeType.ALL, orphanRemoval = true)
	//@Fetch(FetchMode.JOIN)
	//@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	@IndexedEmbedded
	public SchoolRankInSpeciality getSchoolRankInSpeciality() {
		return schoolRankInSpeciality;
	}

	public void setSchoolRankInSpeciality(SchoolRankInSpeciality schoolRankInSpeciality) {
		this.schoolRankInSpeciality = schoolRankInSpeciality;
	}
	
	public School() {
	}

	public School(String name) {
		this.name = name;
	}

	public School(Integer id, String name, String type, String city, String state,
			String setting, Integer size, Integer tuitionFee,
			Integer roomBoard, String applicationDeadline,
			Integer applicationFee, Integer toefl, Integer sat1Percentile25,
			Integer sat1Percentile75, Integer sat2, Float acceptRate,
			Integer rankOverall, Float reputationScore, String selectivity,
			Integer hsClassTop10Percentage, Float studentFacultyRatio,
			String category, String intFinacialAid, String calendar,
			String website) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.city = city;
		this.state = state;
		this.setting = setting;
		this.size = size;
		this.tuitionFee = tuitionFee;
		this.roomBoard = roomBoard;
		this.applicationDeadline = applicationDeadline;
		this.applicationFee = applicationFee;
		this.sat1Percentile25 = sat1Percentile25;
		this.sat1Percentile75 = sat1Percentile75;
		this.numberOfRequiredSat2 = sat2;
		this.acceptRate = acceptRate;
		this.rankOverall = rankOverall;
		this.reputationScore = reputationScore;
		this.selectivity = selectivity;
		this.hsClassTop10Percentage = hsClassTop10Percentage;
		this.studentFacultyRatio = studentFacultyRatio;
		this.category = category;
		this.calendar = calendar;
		this.website = website;
		this.totalCost=tuitionFee+roomBoard;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof School))
			return false;
		School castOther = (School) other;

		return ((this.getName() == castOther.getName()) || 
				(this.getName() != null	&& castOther.getName() != null && this.getName().equals(
				castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "Applicant [name=" + name + ", type=" + type + ", city=" + city
				+ ", state=" + state + ", setting=" + setting + ", size="
				+ size + ", tuitionFee=" + tuitionFee + ", roomBoard="
				+ roomBoard + ", applicationDeadline=" + applicationDeadline
				+ ", applicationFee=" + applicationFee 
				+ ", sat1Percentile25=" + sat1Percentile25 + ", sat1Percentile75="
				+ sat1Percentile75 + ", sat2=" + numberOfRequiredSat2 + ", acceptRate="
				+ acceptRate + ", rankOverall=" + rankOverall
				+ ", reputationScore=" + reputationScore + ", selectivity="
				+ selectivity + ", hsClassTop10Percentage=" + hsClassTop10Percentage
				+ ", studentFacultyRatio=" + studentFacultyRatio
				+ ", category=" + category + ", intFinacialAid="
				+ ", calendar=" + calendar + ", website="
				+ website + "]";
	}
	
	/*public static class RankComparator implements Comparator<Applicant>{
	   public int compare(Applicant school1, Applicant school2){
		   
		  if(school1 == null)
			 return 1;
		  if(school2 == null)
			 return -1; 
		  if(school1.getRankOverall() == null && school2.getRankOverall() == null)
		  	 return 0;
		  //if(school1.getRankOverall() == null)
			// return 1; 
		  //if(school2.getRankOverall() == null)
			 return -1;
		  //if(school1.getRankOverall() == school2.getRankOverall())
			 return 0;//school1.getName().compareTo(school2.getName());
		  if((school1.getRankOverall() == 0 || school1.getRankOverall() == -1) || school1.getRankOverall() > school2.getRankOverall())
			 return 1; 
		  if((school2.getRankOverall() == 0 || school2.getRankOverall() == -1) || school1.getRankOverall() < school2.getRankOverall())
			 return -1;
		 // if(school1.getRankOverall() < school2.getRankOverall())
		//	 return -1;
		  //if(school1.getRankOverall() > school2.getRankOverall())
			// return 1;		  
		  else
		     return 1;
	   }
	}
	
	public static class RankComparator implements Comparator<Applicant>{
	   public int compare(Applicant school1, Applicant school2){
		   int cmp = 1;
		   int school1Rank = school1.getRankOverall() == 0 ? 10000 : school1.getRankOverall() == -1 ? 10001 : school1.getRankOverall();
		   int school2Rank = school2.getRankOverall() == 0 ? 10000 : school2.getRankOverall() == -1 ? 10001 : school2.getRankOverall();
		   
		   if((school1.getRankOverall() == 0 || school1.getRankOverall() == -1))
			   cmp = 1; 
		   else if((school2.getRankOverall() == 0 || school2.getRankOverall() == -1))
			   cmp = -1; 
		   else {
			   cmp = school1.getRankOverall().compareTo(school2.getRankOverall());
		       if (cmp == 0) 
		           cmp = school1.getName().compareTo(school2.getName());
		   }
		   return cmp;	   
	   }
	}
	*/
	
	public static class RankComparator implements Comparator<School>{
		   public int compare(School school1, School school2){
			   Integer school1Rank = school1.getRankOverall() == 0 ? 10000 : school1.getRankOverall() == -1 ? 10001 : school1.getRankOverall();
			   Integer school2Rank = school2.getRankOverall() == 0 ? 10000 : school2.getRankOverall() == -1 ? 10001 : school2.getRankOverall();
		       int cmp = school1Rank.compareTo(school2Rank);
			   if (cmp == 0) 
			       cmp = school1.getName().compareTo(school2.getName());
			   return cmp;	   
		   }
	}		   
	
	public static class RankByCategoryComparator implements Comparator<School>{
		   public int compare(School school1, School school2){
			   Integer school1Rank = school1.getRankOverall() == 0 ? 10000 : school1.getRankOverall() == -1 ? 10001 : school1.getRankOverall();
			   Integer school2Rank = school2.getRankOverall() == 0 ? 10000 : school2.getRankOverall() == -1 ? 10001 : school2.getRankOverall();
		       int cmp = school1.getCategory().compareToIgnoreCase(school2.getCategory());
			   if(cmp == 0){
				  cmp = school1Rank.compareTo(school2Rank);
			      if (cmp == 0) 
				      cmp = school1.getName().compareTo(school2.getName());
			   }   
			   return cmp;	   
		   }
	}
	
	public static class GpaComparator implements Comparator<School>{
	   public int compare(School school1, School school2){
		  int cmp = 1;
		  Float gpa1 = (school1.getAverageGpa() == null || school1.getAverageGpa() == 0.0)? 100.f : school1.getAverageGpa();
		  Float gpa2 = (school2.getAverageGpa() == null || school2.getAverageGpa() == 0.0)? 100.f : school2.getAverageGpa();
          cmp = gpa1.compareTo(gpa2);
		  if (cmp == 0) 
 	          cmp = school1.getRankOverall().compareTo(school2.getRankOverall());
		  return cmp;	   
	   }
	}	
	
	public static class AcceptanceRateComparator implements Comparator<School>{
	   public int compare(School school1, School school2){
		  if(school1 == null)
			 return 1;
		  if(school2 == null)
			 return -1; 
		  if(school1.getAcceptRate() == null && school2.getAcceptRate() == null)
			 return 0;
		  if(school1.getAcceptRate() == null)
			 return 1;
		  if(school2.getAcceptRate() == null)
			 return -1;			 
		  if(school1.getAcceptRate() < school2.getAcceptRate())
		  	 return -1;
		  if (school1.getAcceptRate() > school2.getAcceptRate())
			 return 1;
		  if (school1.getAcceptRate() == school2.getAcceptRate())
			 return school1.getRankOverall().compareTo(school2.getRankOverall());
		  else
			 return 1; 
	   }
	}
	

	public static class NameComparator implements Comparator<School>{
	   public int compare(School school1, School school2){
		  return school1.getName().compareToIgnoreCase(school2.getName());
	   }
	}
	
	public static class TotalCostComparator implements Comparator<School>{
	   public int compare(School school1, School school2){
		  if(school1 == null)
			 return 1;
		  if(school2 == null)
			 return -1; 
		  if(school1.getTotalCost() == null && school2.getTotalCost() == null)
			 return 0;
		  if(school1.getTotalCost() == null)
			 return 1;
		  if(school2.getTotalCost() == null)
			 return -1;			 
		  if(school1.getTotalCost() < school2.getTotalCost())
		  	 return -1;
		  if (school1.getTotalCost() > school2.getTotalCost())
			 return 1;
		  if (school1.getTotalCost() == school2.getTotalCost())
			 return school1.getRankOverall().compareTo(school2.getRankOverall());
		  else
			 return 1; 
	  }
	}
	
	public static class ToeflComparator implements Comparator<School>{
	   public int compare(School school1, School school2){
		  if(school1 == null || school1.getInternationalStudentApplication() == null)
			 return 1;
		  if(school2 == null || school2.getInternationalStudentApplication() == null)
			 return -1; 
		  if(school1.getInternationalStudentApplication().getMinimumToeflScore() == null && school2.getInternationalStudentApplication().getMinimumToeflScore() == null)
			 return 0;
		  if(school1.getInternationalStudentApplication().getMinimumToeflScore() == null)
			 return 1;
		  if(school2.getInternationalStudentApplication().getMinimumToeflScore() == null)
			 return -1;			 
		  if(school1.getInternationalStudentApplication().getMinimumToeflScore() < school2.getInternationalStudentApplication().getMinimumToeflScore())
		  	 return -1;
		  if(school1.getInternationalStudentApplication().getMinimumToeflScore() > school2.getInternationalStudentApplication().getMinimumToeflScore())
			 return 1;
		  if(school1.getInternationalStudentApplication().getMinimumToeflScore() == school2.getInternationalStudentApplication().getMinimumToeflScore())
	  		 return school1.getRankOverall().compareTo(school2.getRankOverall());
		  else
			 return 1; 
	  }
	}
	
	public static class SatComparator implements Comparator<School>{
		   public int compare(School school1, School school2){
			  if(school1 == null)
				 return 1;
			  if(school2 == null)
				 return -1; 
			  if(school1.getAverageSAT() == null && school2.getAverageSAT() == null)
				 return 0;
			  if(school1.getAverageSAT() == null)
				 return 1;
			  if(school2.getAverageSAT() == null)
				 return -1;			 
			  //if(school1.getSat1Percentile25() < school2.getSat1Percentile25())
			  //   return -1;
			  //if (school1.getSat1Percentile25() > school2.getSat1Percentile25())
			  //    return 1;
			  if (school1.getAverageSAT().equals(school2.getAverageSAT()))
				 return school1.getRankOverall().compareTo(school2.getRankOverall());
			  else
				 return school1.getAverageSAT().compareTo(school2.getAverageSAT()); 
		  }
		}
	
	public static class SpecialityRankComparator implements Comparator<School>{
	   public int compare(School school1, School school2){
		  int result = 1;
		  if(school1.getSchoolRankInSpeciality().getRank() > 0){
	         try{
		        if(school1.getSchoolRankInSpeciality().getRank() < school2.getSchoolRankInSpeciality().getRank())
		     	   result = -1;
			    else if(school1.getSchoolRankInSpeciality().getRank() > school2.getSchoolRankInSpeciality().getRank())
			       result = 1;
			    else
			       result = school1.getName().compareTo(school2.getName());
			       
			      // if(result == 0){
			    	//  if(school1.getName().compareTo(school2.getName()) < 0)
			    		// result = -1; 
			    	  //else if(school1.getName().compareTo(school2.getName()) > 0)
				    	// result = 1;
			    	  //else
			    		//  result = 0;
			       //}  
			 }
			 catch(Exception e){
			    e.printStackTrace();
			 }	
		   } 
		   return result;
		}
	  }
	
	/*
	public static class SpecialityRankComparator implements Comparator<Applicant>{
		   public int compare(Applicant school1, Applicant school2){
			  if(school1 == null)
				 return 1;
			  if(school2 == null)
				 return -1; 
			  if(school1.getSchoolRankInSpeciality() == null && school2.getSchoolRankInSpeciality() == null)
				 return 0;
			  if(school1.getSchoolRankInSpeciality() == null)
				 return 1;
			  if(school2.getSchoolRankInSpeciality() == null)
				 return -1;			 
			  if(school1.getSchoolRankInSpeciality().getRank() > 0){
		         if(school1.getSchoolRankInSpeciality().getRank() < school2.getSchoolRankInSpeciality().getRank())
			    	return -1;
				 else if(school1.getSchoolRankInSpeciality().getRank() > school2.getSchoolRankInSpeciality().getRank())
				    return 1;
				 else if(school1.getSchoolRankInSpeciality().getRank() == school2.getSchoolRankInSpeciality().getRank())
				    return school1.getName().compareTo(school2.getName());
			  } 
			  return 1;   
			}
		  }
	*/	  
}
